name: Build PDF
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: src/resume.tex
          # uncomment the next line if you use system fonts or want xelatex
          # latexmk_use_xelatex: true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: src/*.pdf